name: Build and Deploy

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
      
    - name: Generate package-lock.json if it doesn't exist
      run: |
        if [ ! -f package-lock.json ]; then
          npm install --package-lock-only
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          git commit -m "Add package-lock.json" || echo "No changes to commit"
          git push || echo "No changes to push"
        fi
    
    - name: Lint
      run: npm run lint || echo "No lint script found, skipping"
    
    - name: Type check
      run: npm run type-check || echo "No type-check script found, skipping"
    
    - name: Test
      run: npm test || echo "No test script found, skipping"
    
    - name: Build
      run: npm run build || echo "No build script found, skipping"
    
    - name: Deploy to Firebase Staging
      if: github.ref == 'refs/heads/development'
      run: |
        npm install -g firebase-tools
        firebase use staging --token ${{ secrets.FIREBASE_TOKEN }} || echo "Firebase project not configured, skipping"
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} || echo "Firebase deployment not configured, skipping"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}