name: Firebase Functions CI/CD

on:
  push:
    branches: [ development, test, main ]
    paths:
      - 'backend/functions/**'
  pull_request:
    branches: [ development, test, main ]
    paths:
      - 'backend/functions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/functions
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './backend/functions/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy to Firebase Functions (Test)
        if: github.ref == 'refs/heads/test'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project lorepin-staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase Functions (Production)
        if: github.ref == 'refs/heads/main'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project lorepin-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}