name: Firebase Functions CI/CD

on:
  push:
    branches: [ development, test, main ]
    paths:
      - 'functions/**'
      - '.github/workflows/functions.yml'
  pull_request:
    branches: [ development, test, main ]
    paths:
      - 'functions/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './functions/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Test
        run: npm test
      
      - name: Build
        run: npm run build
  
  deploy-to-test:
    needs: build-and-test
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase Test
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project lorepin-staging
  
  deploy-to-production:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase Production
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project lorepin-prod